name: save
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  fl_chart: ^0.55.2
  
 
  workmanager: 0.5.2
  
  permission_handler: ^11.3.1
  http: ^1.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.0
  cached_network_image: ^3.3.1
  pdf: ^3.10.8
 


  path_provider: ^2.1.4
  open_file: ^3.3.2
  google_sign_in: ^6.3.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
firebase_core: ^3.6.0
firebase_auth: ^5.3.1
google_sign_in: ^6.2.1
firebase_crashlytics: ^4.3.5
firebase_analytics: ^11.4.5
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/